# EVOLVE-BLOCK-START
import itertools
import numpy as np


def heilbronn_triangle11() -> np.ndarray:
    """
    Deterministically maximize the minimum normalized triangle area for eleven
    points by globally exploring barycentric coordinates, then polishing the
    best candidates from several distinct DE populations with fixed-orientation
    maximin SLSQP subproblems.
    """
    try:
        from scipy.optimize import differential_evolution, minimize
    except Exception:
        # A valid deterministic fallback if SciPy is unavailable.
        h = np.sqrt(3.0) / 2.0
        return np.array([
            [0.0, 0.0], [1.0, 0.0], [0.5, h],
            [0.164, 0.105], [0.431, 0.071], [0.742, 0.103],
            [0.096, 0.341], [0.355, 0.286], [0.657, 0.319],
            [0.246, 0.580], [0.524, 0.603],
        ], dtype=float)

    h = np.sqrt(3.0) / 2.0
    triples = np.asarray(list(itertools.combinations(range(11), 3)), dtype=int)
    i0, i1, i2 = triples.T

    # The first three points are the corners.  For each remaining point,
    # u,v in [0,1] are converted to nonnegative barycentric coordinates:
    # (a,b,c) = (1-u, u(1-v), uv).
    def decode(x):
        q = np.asarray(x, dtype=float).reshape(8, 2)
        u = q[:, 0]
        v = q[:, 1]
        b = u * (1.0 - v)
        c = u * v
        interior = np.column_stack((b + 0.5 * c, h * c))
        return np.vstack((
            np.array([[0.0, 0.0], [1.0, 0.0], [0.5, h]]),
            interior,
        ))

    def normalized_signed_areas(points):
        a = points[i1] - points[i0]
        b = points[i2] - points[i0]
        # |cross| / (2 * area of the unit equilateral container)
        return (a[:, 0] * b[:, 1] - a[:, 1] * b[:, 0]) / h

    def quality(x):
        return float(np.min(np.abs(normalized_signed_areas(decode(x)))))

    best_x = None
    best_value = -np.inf
    # Retain several genuinely different DE basins.  Fixed-sign SLSQP is a
    # local method, so polishing only the globally best DE member wastes much
    # of the useful diversity generated by the independent populations.
    finalists = []
    bounds = [(0.001, 0.999)] * 16

    # Several medium-sized deterministic searches are more reliable on this
    # highly nonsmooth maximin objective than one single long population run.
    for seed in (1701, 2718, 3141, 5772):
        result = differential_evolution(
            lambda x: -quality(x),
            bounds,
            seed=seed,
            strategy="best1bin",
            popsize=24,
            maxiter=1250,
            mutation=(0.35, 1.45),
            recombination=0.90,
            tol=1.0e-7,
            polish=False,
            updating="immediate",
            workers=1,
        )
        value = quality(result.x)
        if value > best_value:
            best_value = value
            best_x = result.x.copy()

        # The DE population is already sorted only indirectly through its
        # energies; retain its two strongest members for independent local
        # orientation-cell polishing below.
        population = np.asarray(result.population)
        energies = np.asarray(result.population_energies)
        for index in np.argsort(energies)[:2]:
            finalists.append(population[index].copy())

    # Locally replace the nonsmooth min objective by an explicit lower-bound
    # variable t and one smooth signed-area constraint per point triple.
    # Triangle orientations cannot change near a positive-area solution.
    # Exactly eight SLSQP calls as before, but each begins in an actual
    # high-quality DE basin rather than from potentially destructive random
    # perturbations of one basin.
    for start in finalists:
        signs = np.sign(normalized_signed_areas(decode(start)))
        signs[signs == 0.0] = 1.0
        t0 = quality(start) * 0.995
        z0 = np.concatenate((start, [t0]))

        def constraints(z, fixed_signs=signs):
            return fixed_signs * normalized_signed_areas(decode(z[:-1])) - z[-1]

        polished = minimize(
            lambda z: -z[-1],
            z0,
            method="SLSQP",
            bounds=bounds + [(0.0, 0.20)],
            constraints={"type": "ineq", "fun": constraints},
            options={"maxiter": 2500, "ftol": 3.0e-13, "disp": False},
        )
        candidate = polished.x[:-1] if polished.x is not None else start
        value = quality(candidate)
        if value > best_value:
            best_value = value
            best_x = candidate.copy()

    return decode(best_x)


# EVOLVE-BLOCK-END
